# Generated by Django 4.2.7 on 2024-03-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('item_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('base_distance_in_km', models.IntegerField(default=5)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.organization')),
            ],
        ),
    ]
