# Generated by Django 4.2.7 on 2024-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='km_in_price',
        ),
    ]
